/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regexjava;

import org.junit.Test;
import static org.junit.Assert.*;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import regexjava.RegexPrepper;

public class AppTest {
    @Test public void testPostfix() throws ClassNotFoundException, NoSuchMethodException, SecurityException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {
        Class<?> prepperClass = Class.forName("regexjava.RegexPrepper");
        Class[] arg = {String.class};  
        Method method = prepperClass.getDeclaredMethod("toPostfix", arg);
        method.setAccessible(true);


        assertEquals( "AB+",method.invoke(null, "A+B"));
        assertEquals( "AB+C+",method.invoke(null, "A+B+C"));
    }

    @Test public void TestConcat() throws ClassNotFoundException, NoSuchMethodException, SecurityException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
    {
        Class<?> prepperClass = Class.forName("regexjava.RegexPrepper");
        Class[] arg = {String.class};  
        Method method = prepperClass.getDeclaredMethod("addExplicitConcat", arg);
        method.setAccessible(true);

        assertEquals( "A.B",method.invoke(null, "AB"));
        assertEquals( "A.B.C",method.invoke(null, "ABC"));
        assertEquals("A.B+C", method.invoke(null, "AB+C"));
    }

}
