/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regexjava;

import org.junit.Test;
import static org.junit.Assert.*;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class AppTest {
    @Test public void testA()
    {
        assertEquals(true, true);
    }
}
