/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regexjava;

import java.util.Scanner;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

import PCREgrammar.PCREgrammarLexer;
import PCREgrammar.PCREgrammarParser;

public class App {
    public static void main(String[] args)
    {
        Scanner scanner = new Scanner(System.in);
        System.out.printf("Insert a regex: ");
        String expr = scanner.nextLine();
        
        CharStream stream = CharStreams.fromString(expr);
        PCREgrammarLexer lexer = new PCREgrammarLexer(stream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        PCREgrammarParser parser = new PCREgrammarParser(tokens);
        ParseTree tree = parser.parse();
        
        System.out.println("\n=== Parse Tree ===");
        System.out.println(TreeUtils.toPrettyTree(tree, parser));
        
        CodeGenerator cg = new CodeGenerator(expr, tree);
        NFA automata = cg.getAutomata();
        System.out.println("\n=== NFA ===");
        automata.print();
        
        String default_path = System.getProperty("user.home") + "\\Desktop\\generated.c";
        System.out.println("\n=== Source Code Generator ===");
        System.out.println("Sucessfully generated a matcher for \\" + expr + "\\ in " + default_path);
        cg.generate(default_path);
        scanner.close();
    }

}
