/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regexjava;

import java.util.Scanner;

public class App {
    public static void main(String[] args)
    {
        Scanner scanner = new Scanner(System.in);
        System.out.printf("Insert a regex: ");
        String expr = scanner.nextLine();
        CodeGenerator cg = new CodeGenerator(expr);
        System.out.println("");
        cg.generate();
        scanner.close();
    }

}
