/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regexjava;

import org.jgrapht.*;
import org.jgrapht.graph.*;

public class App {
    public static void main(String[] args) {
        System.out.println(RegexPrepper.prep("AB+C"));
    }

}
